### ISSUE TITLE
Help needed with V2 :(

### ISSUE THREAD

**Issue by muhammedjenos** [m4rvr/storyblok-rich-text-renderer#25]
I have had the v2 version implemented for a while now in a Nuxt 2 project and everything was working fine until couple of days ego. Now the rich text renderer give warnings like:

```
[Vue warn]: The setup binding property "linkType" is already declared.

found in

<SbLink>
       <SbParagraph>
         <SbDocument>
          ...
             ...
```

not just linkType but all other tags as well. Refreshing the page a server error warning with the console now showing 

```
TypeError: Cannot add property _Ctor, object is not extensible 
    at t.extend (3fc59dc.js:2:42246)
```

I have deleted and reinstalled node packages, tried different version of composition-api etc..etc..and now run out of options. 

Could some expert here point me to the right direction what could be the issue?

**Comment by muhammedjenos** [comment]
Solved.
Vue version 2.7 mess up with the composition api plugin. Keep Vue at 2.6.14 and below and the plugin worked as expected

**Comment by muhammedjenos** [comment]
Hi @deodat,
I uninstalled vue and re-installed 2.6.14 and locked the version.
In package.json:  "vue": "2.6.14"

**Comment by kubyshkin1994** [comment]
For `"nuxt": "^2.15.8"`

1. Uninstall Vue packages
`yarn remove vue vue-server-renderer vue-template-compiler` or `npm uninstall vue vue-server-renderer vue-template-compiler`

2. Re-install Vue packages version 2.6.14
`yarn add vue@2.6.14 vue-server-renderer@2.6.14 vue-template-compiler@2.6.14` or `npm install vue@2.6.14 vue-server-renderer@2.6.14 vue-template-compiler@2.6.14`

3. In `package.json` lock versions

If you use yarn, use `resolutions`
```
"resolutions": {
  "vue": "2.6.14",
  "vue-server-renderer": "2.6.14",
  "vue-template-compiler": "2.6.14"
}
```
If you use npm, use `overrides`
```
"overrides": {
  "vue": "2.6.14",
  "vue-server-renderer": "2.6.14",
  "vue-template-compiler": "2.6.14"
}
```

5. Then delete your package manager's lock file
`rm -f yarn.lock`

6. And reinstall it
`yarn install` or `npm install`

**Comment by katerlouis** [comment]
@muhammedjenos dumb question: how do you install v2 of this plugin? 
`$ npm install @marvr/storyblok-rich-text-vue-renderer@2.0.1` doesn't seem to do the trick?
