### ISSUE TITLE
New features added in recent Richtext update

### ISSUE THREAD

**Issue by kubyshkin1994** [m4rvr/storyblok-rich-text-renderer#27]
[Storyblok V2: Update 9](https://www.storyblok.com/changelog#cl/storyblok-v2-update-9)

New features:
- Subscript
- Superscript
- Text color
- Highlight
- Emoji

Is there any solution to resolve these types in version 2.0.1?

**Comment by madebyfabian** [comment]
It should be pretty easy to integrate it, I just opened a PR to add the new Anchor Marks. #32 Once this is merged and working, I could add more.

**Comment by madebyfabian** [comment]
- Superscript
- Subscript
- Anchor
Are now support within the latest verison of this package (v3.4.0)

**Comment by madebyfabian** [comment]
- Text Color
- Highlight

Are now also implemented (v3.5.0)

**Comment by madebyfabian** [comment]
- Emoji

Is now also supported (v3.6.0)

I know it's not supported in the v2 version, but since this is discontinued by the original author.
